### ISSUE TITLE
log 폴더 .gitIgnore 적용하기

### ISSUE THREAD

**Issue by seyoung5744** [WishMarket/WishMarket-BE#7]
##  이슈 내용

log 파일까지 GitHub에 올릴 필요 없기 때문에 .gitIgnore에 추가할 필요가 있음

![image](https://user-images.githubusercontent.com/53173850/217473141-33198666-db70-4b14-b224-f6c6f376c4b5.png)

<br>

##  작업 사항
- [ ] gitIgnore 적용
- #10 

<br>

**Comment by Ko-udon** [comment]
log파일이 올라갈 필요가 없었군요 
확인하였습니다~
